Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: <em>Heyzap Hackday App by Max Tagher — Released to <a href="https://creativecommons.org/publicdomain/zero/1.0/">the public domain</a></em>
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
